### ISSUE TITLE
返回的代码可以格式化一下。

### ISSUE THREAD

**Issue by hurrykee** [XinRoom/OpenAiChat#1]
I: | 用JavaScript实现正则表达式过滤标点符号和空格，问号除外。
-- | --
Bot: | ```js let str = 'Hello? This is a test string. '; let result = str.replace(/[^\w\s?!]/g, ''); console.log(result); // Hello? This is a test string? ```

**Comment by XinRoom** [comment]
因为返回值不一定是md形式，所以就没有进行格式化
